steps:
  # Cloud Build でビルド
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: [
        "-c",
        "docker build \
        -f Dockerfile.production
        -t gcr.io/${PROJECT_ID}/${_SERVICE_NAME} \
        --build-arg PORT=8080 \
        --build-arg RAILS_MASTER_KEY=$$RAILS_MASTER_KEY \
        --build-arg RAILS_ENV=production \
        --build-arg GOOGLE_PROJECT_ID=${PROJECT_ID} \
        --build-arg CLOUD_SQL_CONNECTION_NAME=${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME} \
        --build-arg FIREBASE_PROJECT_ID=$$FIREBASE_PROJECT_ID \
        --build-arg FRONTEND_URL=$$FRONTEND_URL \
        --build-arg VIMEO_FOLDER_ID=$$VIMEO_FOLDER_ID \
        --build-arg VIMEO_ACCESS_TOKEN=$$VIMEO_ACCESS_TOKEN \
        --build-arg INFO_GMAIL_ADDRESS=$$INFO_GMAIL_ADDRESS \
        --build-arg INFO_GMAIL_PASSWORD=$$INFO_GMAIL_PASSWORD \
        --build-arg GOOGLE_ACCOUNT_TYPE=$$GOOGLE_ACCOUNT_TYPE \
        --build-arg GOOGLE_CLIENT_ID=$$GOOGLE_CLIENT_ID \
        --build-arg GOOGLE_CLIENT_EMAIL=$$GOOGLE_CLIENT_EMAIL \
        --build-arg 'GOOGLE_PRIVATE_KEY=$$GOOGLE_PRIVATE_KEY' \
        --build-arg STORAGE_BUCKET_NAME=$$STORAGE_BUCKET_NAME \
        --build-arg STORAGE_PROJECT_ID=$$STORAGE_PROJECT_ID \
        --build-arg STORAGE_PRIVATE_KEY_ID=$$STORAGE_PRIVATE_KEY_ID \
        --build-arg 'STORAGE_PRIVATE_KEY=$$STORAGE_PRIVATE_KEY' \
        --build-arg STORAGE_CLIENT_EMAIL=$$STORAGE_CLIENT_EMAIL \
        --build-arg STORAGE_CLIENT_ID=$$STORAGE_CLIENT_ID \
        --build-arg STORAGE_CLIENT_X509_CERT_URL=$$STORAGE_CLIENT_X509_CERT_URL \
        --build-arg STRIPE_PRODUCT_ID=$$STRIPE_PRODUCT_ID \
        --build-arg STRIPE_PUBLIC_KEY=$$STRIPE_PUBLIC_KEY \
        --build-arg STRIPE_SECRET_KEY=$$STRIPE_SECRET_KEY \
        --build-arg DATABASE_NAME=$$DATABASE_NAME \
        --build-arg DATABASE_USERNAME=$$DATABASE_USERNAME \
        --build-arg DATABASE_PASSWORD=$$DATABASE_PASSWORD \
        --build-arg SENTRY_URL=$$SENTRY_URL \
        . \
        ",
      ]
    secretEnv:
      [
        "RAILS_MASTER_KEY",
        "FIREBASE_PROJECT_ID",
        "FRONTEND_URL",
        "INFO_GMAIL_ADDRESS",
        "INFO_GMAIL_PASSWORD",
        "GOOGLE_ACCOUNT_TYPE",
        "GOOGLE_CLIENT_ID",
        "GOOGLE_CLIENT_EMAIL",
        "GOOGLE_PRIVATE_KEY",
        "STORAGE_BUCKET_NAME",
        "STORAGE_PROJECT_ID",
        "STORAGE_PRIVATE_KEY_ID",
        "STORAGE_PRIVATE_KEY",
        "STORAGE_CLIENT_EMAIL",
        "STORAGE_CLIENT_ID",
        "STORAGE_CLIENT_X509_CERT_URL",
        "VIMEO_FOLDER_ID",
        "VIMEO_ACCESS_TOKEN",
        "STRIPE_PRODUCT_ID",
        "STRIPE_PUBLIC_KEY",
        "STRIPE_SECRET_KEY",
        "DATABASE_NAME",
        "DATABASE_USERNAME",
        "DATABASE_PASSWORD",
        "SENTRY_URL",
      ]
  # Container Registry にアップロード
  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]
  # db:migrate
  - id: "apply migrations"
    name: "gcr.io/google-appengine/exec-wrapper"
    entrypoint: "bash"
    args:
      [
        "-c",
        "/buildstep/execute.sh -i gcr.io/${PROJECT_ID}/${_SERVICE_NAME} -s ${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME} -e RAILS_MASTER_KEY=$$RAILS_MASTER_KEY -- bundle exec rails db:migrate",
      ]
    secretEnv: ["RAILS_MASTER_KEY"]

substitutions:
  _REGION: asia-northeast1
  _SERVICE_NAME: buson-online-salon-api
  _INSTANCE_NAME: buson-online-salon-sql

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/RAILS_MASTER_KEY/versions/latest
      env: RAILS_MASTER_KEY
    - versionName: projects/${PROJECT_ID}/secrets/FIREBASE_PROJECT_ID/versions/latest
      env: FIREBASE_PROJECT_ID
    - versionName: projects/${PROJECT_ID}/secrets/FRONTEND_URL/versions/latest
      env: FRONTEND_URL
    - versionName: projects/${PROJECT_ID}/secrets/INFO_GMAIL_ADDRESS/versions/latest
      env: INFO_GMAIL_ADDRESS
    - versionName: projects/${PROJECT_ID}/secrets/INFO_GMAIL_PASSWORD/versions/latest
      env: INFO_GMAIL_PASSWORD
    - versionName: projects/${PROJECT_ID}/secrets/GOOGLE_ACCOUNT_TYPE/versions/latest
      env: GOOGLE_ACCOUNT_TYPE
    - versionName: projects/${PROJECT_ID}/secrets/GOOGLE_CLIENT_ID/versions/latest
      env: GOOGLE_CLIENT_ID
    - versionName: projects/${PROJECT_ID}/secrets/GOOGLE_CLIENT_EMAIL/versions/latest
      env: GOOGLE_CLIENT_EMAIL
    - versionName: projects/${PROJECT_ID}/secrets/GOOGLE_PRIVATE_KEY/versions/latest
      env: GOOGLE_PRIVATE_KEY
    - versionName: projects/${PROJECT_ID}/secrets/STORAGE_BUCKET_NAME/versions/latest
      env: STORAGE_BUCKET_NAME
    - versionName: projects/${PROJECT_ID}/secrets/STORAGE_PROJECT_ID/versions/latest
      env: STORAGE_PROJECT_ID
    - versionName: projects/${PROJECT_ID}/secrets/STORAGE_PRIVATE_KEY_ID/versions/latest
      env: STORAGE_PRIVATE_KEY_ID
    - versionName: projects/${PROJECT_ID}/secrets/STORAGE_PRIVATE_KEY/versions/latest
      env: STORAGE_PRIVATE_KEY
    - versionName: projects/${PROJECT_ID}/secrets/STORAGE_CLIENT_EMAIL/versions/latest
      env: STORAGE_CLIENT_EMAIL
    - versionName: projects/${PROJECT_ID}/secrets/STORAGE_CLIENT_ID/versions/latest
      env: STORAGE_CLIENT_ID
    - versionName: projects/${PROJECT_ID}/secrets/STORAGE_CLIENT_X509_CERT_URL/versions/latest
      env: STORAGE_CLIENT_X509_CERT_URL
    - versionName: projects/${PROJECT_ID}/secrets/VIMEO_FOLDER_ID/versions/latest
      env: VIMEO_FOLDER_ID
    - versionName: projects/${PROJECT_ID}/secrets/VIMEO_ACCESS_TOKEN/versions/latest
      env: VIMEO_ACCESS_TOKEN
    - versionName: projects/${PROJECT_ID}/secrets/STRIPE_PRODUCT_ID/versions/latest
      env: STRIPE_PRODUCT_ID
    - versionName: projects/${PROJECT_ID}/secrets/STRIPE_PUBLIC_KEY/versions/latest
      env: STRIPE_PUBLIC_KEY
    - versionName: projects/${PROJECT_ID}/secrets/STRIPE_SECRET_KEY/versions/latest
      env: STRIPE_SECRET_KEY
    - versionName: projects/${PROJECT_ID}/secrets/DATABASE_NAME/versions/latest
      env: DATABASE_NAME
    - versionName: projects/${PROJECT_ID}/secrets/DATABASE_USERNAME/versions/latest
      env: DATABASE_USERNAME
    - versionName: projects/${PROJECT_ID}/secrets/DATABASE_PASSWORD/versions/latest
      env: DATABASE_PASSWORD
    - versionName: projects/${PROJECT_ID}/secrets/SENTRY_URL/versions/latest
      env: SENTRY_URL
images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"
